---
output:
  html_document:
    latex_engine: xelatex
  pdf_document: 
    latex_engine: xelatex
---
```{r}
#library(knitr)
```
---
title: "Project: DS504"
author: "Danielle Angelini"
output:
  html_document:
    latex_engine: xelatex
  pdf_document: 
    latex_engine: xelatex
---

#Data Processing
```{r}
games_csv = "C:/Users/deang/Documents/DS504/Project/games.csv"
games_read = read.csv(games_csv)
games_data = as.data.frame(games_read)

ranking_csv = "C:/Users/deang/Documents/DS504/Project/ranking.csv"
ranking_read = read.csv(ranking_csv)
ranking_data = as.data.frame(ranking_read)
```

```{r}
summary(games_data)
```

```{r}
library(dplyr)
rankings = ranking_data %>% select(TEAM_ID, STANDINGSDATE, G, W, L, W_PCT, HOME_RECORD, ROAD_RECORD)
master_games = merge(x = games_data, y = rankings, by.x = c("GAME_DATE_EST","HOME_TEAM_ID"), by.y = c("STANDINGSDATE","TEAM_ID"))
```

```{r}
master_games <- master_games %>% rename("HT_G" = "G", "HT_W" = "W", "HT_L" = "L", "HT_W_PCT" = "W_PCT", "HT_HOME_RECORD" = "HOME_RECORD", "HT_ROAD_RECORD" = "ROAD_RECORD") 
```

```{r}
master_games <- master_games[, c(1,2,3,4,5,6,7,22,23,24,25,26,27,8,9,10,11,12,13,14,15,16,17,18,19,20,21)]
```

```{r}
master_games = merge(x = master_games, y = rankings, by.x = c("GAME_DATE_EST","VISITOR_TEAM_ID"), by.y = c("STANDINGSDATE","TEAM_ID"))
```

```{r}
master_games <- master_games %>% rename("AT_G" = "G", "AT_W" = "W", "AT_L" = "L", "AT_W_PCT" = "W_PCT", "AT_HOME_RECORD" = "HOME_RECORD", "AT_ROAD_RECORD" = "ROAD_RECORD") 
```

```{r}
master_games <- master_games[, c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,28,29,30,31,32,33,21,22,23,24,25,26,27)]
```

```{r}
#Removing Duplicate Games
games_dist = n_distinct(master_games$GAME_ID)
master_games_2 = master_games[!duplicated(master_games$GAME_ID),]
```

```{r}
#Imputating data
#Columns with NA: PTS_home, FG_PCT_home , FT_PCT_home, FG3_PCT_home, AST_home, REB_home, etc for away too
#Looks like 99 whole games have missing data, so just remove games

master_games_NA = master_games_2 %>% filter(is.na(PTS_home))
head(master_games_NA)
```

```{r}
master_games_3 = na.omit(master_games_2)
```

```{r}
#Correlation Between Home and Away: 
cor(master_games_3[sapply(master_games_3, is.numeric)])
```

```{r}
#Outlier detection
library(ggplot2)

ggplot(master_games_3, aes(PTS_home)) +
  geom_histogram(color = "#000000", fill = "#0099F8") +
  ggtitle("PTS_home distribution") +
  theme_classic() +
  theme(plot.title = element_text(size = 18))

ggplot(master_games_3, aes(FG_PCT_home)) +
  geom_histogram(color = "#000000", fill = "#0099F8") +
  ggtitle("FG_PCT_home distribution") +
  theme_classic() +
  theme(plot.title = element_text(size = 18))

ggplot(master_games_3, aes(FT_PCT_home)) +
  geom_histogram(color = "#000000", fill = "#0099F8") +
  ggtitle("FT_PCT_home distribution") +
  theme_classic() +
  theme(plot.title = element_text(size = 18))

ggplot(master_games_3, aes(FG3_PCT_home)) +
  geom_histogram(color = "#000000", fill = "#0099F8") +
  ggtitle("FG3_PCT_home distribution") +
  theme_classic() +
  theme(plot.title = element_text(size = 18))

ggplot(master_games_3, aes(REB_home)) +
  geom_histogram(color = "#000000", fill = "#0099F8") +
  ggtitle("REB_home distribution") +
  theme_classic() +
  theme(plot.title = element_text(size = 18))

ggplot(master_games_3, aes(AST_home)) +
  geom_histogram(color = "#000000", fill = "#0099F8") +
  ggtitle("AST_home distribution") +
  theme_classic() +
  theme(plot.title = element_text(size = 18))
```

```{r}
cor(master_games_3$PTS_home, master_games_3$HOME_TEAM_WINS)
cor(master_games_3$AST_home, master_games_3$HOME_TEAM_WINS)
cor(master_games_3$REB_home, master_games_3$HOME_TEAM_WINS)
cor(master_games_3$FG_PCT_home, master_games_3$HOME_TEAM_WINS)
cor(master_games_3$FT_PCT_home, master_games_3$HOME_TEAM_WINS)
cor(master_games_3$FG3_PCT_home, master_games_3$HOME_TEAM_WINS)
```

```{r}
# create detect outlier function
test_master = master_games_3
detect_outlier = function(x) {
 
    # calculate first quantile
    Quantile1 = quantile(x, probs=.25)
 
    # calculate third quantile
    Quantile3 = quantile(x, probs=.75)
 
    # calculate inter quartile range
    IQR = Quantile3-Quantile1
 
    # return true or false
    x > Quantile3 + (IQR*1.5) | x < Quantile1 - (IQR*1.5)
}
 
# create remove outlier function
remove_outlier = function(dataframe,
                            columns=names(dataframe)) {
 
    # for loop to traverse in columns vector
    for (col in columns) {
 
        # remove observation if it satisfies outlier function
        dataframe <- dataframe[!detect_outlier(dataframe[[col]]), ]
    }
 
    # return dataframe
    print("Remove outliers")
    print(dataframe)
}
```

```{r}
test_master = remove_outlier(test_master, c('PTS_home', 'PTS_away'))
test_master_2 = remove_outlier(test_master, c('AST_home', 'AST_away'))
test_master_3 = remove_outlier(test_master_2, c('REB_home', 'REB_away'))
test_master_4 = remove_outlier(test_master_3, c('FG_PCT_home', 'FG_PCT_away'))
test_master_5 = remove_outlier(test_master_4, c('FT_PCT_home', 'FT_PCT_away'))
test_master_6 = remove_outlier(test_master_5, c('FG3_PCT_home', 'FG3_PCT_away'))
```

```{r}
#Home/Road Win PCT
library(tidyverse)
master_games_4 = test_master_6 %>% 
  separate(HT_HOME_RECORD, into = c("HT_HOME_W","HT_HOME_L"), sep = "-", convert = TRUE) %>%
  separate(HT_ROAD_RECORD, into = c("HT_ROAD_W","HT_ROAD_L"), sep = "-", convert = TRUE) %>%
  separate(AT_HOME_RECORD, into = c("AT_HOME_W","AT_HOME_L"), sep = "-", convert = TRUE) %>%
  separate(AT_ROAD_RECORD, into = c("AT_ROAD_W","AT_ROAD_L"), sep = "-", convert = TRUE) %>%
  mutate(HT_HOME_W_PCT = round(HT_HOME_W/(HT_HOME_W + HT_HOME_L),3)) %>%
  mutate(HT_ROAD_W_PCT = round(HT_ROAD_W/(HT_ROAD_W + HT_ROAD_L),3)) %>%
  mutate(AT_HOME_W_PCT = round(AT_HOME_W/(AT_HOME_W + AT_HOME_L),3)) %>%
  mutate(AT_ROAD_W_PCT = round(AT_ROAD_W/(AT_ROAD_W + AT_ROAD_L),3))

master_games_4[is.na(master_games_4)] <- 0
master_games_5 = subset(master_games_4, select = -c(HT_HOME_W, HT_HOME_L, HT_ROAD_W, HT_ROAD_L, AT_HOME_W, AT_HOME_L, AT_ROAD_W, AT_ROAD_L))

master_games_5 <- master_games_5[, c(1,2,3,4,5,6,7,8,9,10,11,30,31,12,13,14,15,16,17,18,19,20,21,22,32,33,23,24,25,26,27,28,29)]
```

#make sure to check all calculations!
```{r}
#Total Points Scored Home and Away
library(dplyr)
master_games_5$h_temp_id = paste(master_games_5$HOME_TEAM_ID, master_games_5$SEASON, sep = "-")
cumsum_support = master_games_5 %>% group_by(h_temp_id) %>% mutate(TOT_PTS_HOME = cumsum(PTS_home) - PTS_home)

cumsum_support$a_temp_id = paste(cumsum_support$VISITOR_TEAM_ID, cumsum_support$SEASON, sep = "-")
cumsum_support = cumsum_support %>% group_by(a_temp_id) %>% mutate(TOT_PTS_AWAY = cumsum(PTS_away) - PTS_away)

```

```{r}
#Avg Point Differential
library(dplyr)
cumsum_support = cumsum_support %>% mutate(PTS_DIF_HOME = PTS_home - PTS_away)
cumsum_support = cumsum_support %>% mutate(PTS_DIF_AWAY = PTS_away - PTS_home)
cumsum_support = cumsum_support %>% group_by(h_temp_id) %>% mutate(AVG_PT_DIF_HOME = round(lag(cummean(PTS_DIF_HOME)),3))
cumsum_support = cumsum_support %>% group_by(a_temp_id) %>% mutate(AVG_PT_DIF_AWAY = round(lag(cummean(PTS_DIF_AWAY)),3))

```

```{r}
#AVG_FG_PCT_HOME and AVG_FG_PCT_AWAY
library(dplyr)
cumsum_support = cumsum_support %>% group_by(h_temp_id) %>% mutate(AVG_FG_PCT_HOME = round(lag(cummean(FG_PCT_home)),3))

cumsum_support = cumsum_support %>% group_by(a_temp_id) %>% mutate(AVG_FG_PCT_AWAY = round(lag(cummean(FG_PCT_away)),3))
```

```{r}
#AVG_FT_PCT_HOME and AVG_FT_PCT_AWAY
cumsum_support = cumsum_support %>% group_by(h_temp_id) %>% mutate(AVG_FT_PCT_HOME = round(lag(cummean(FT_PCT_home)),3))

cumsum_support = cumsum_support %>% group_by(a_temp_id) %>% mutate(AVG_FT_PCT_AWAY = round(lag(cummean(FT_PCT_away)),3))
```

```{r}
#AVG_FG3_PCT_HOME and AVG3_FG_PCT_AWAY
cumsum_support = cumsum_support %>% group_by(h_temp_id) %>% mutate(AVG_FG3_PCT_HOME = round(lag(cummean(FG3_PCT_home)),3))

cumsum_support = cumsum_support %>% group_by(a_temp_id) %>% mutate(AVG_FG3_PCT_AWAY = round(lag(cummean(FG3_PCT_away)),3))
```

```{r}
#TOT_AST_HOME and TOT_AST_AWAY
cumsum_support = cumsum_support %>% group_by(h_temp_id) %>% mutate(TOT_AST_HOME = cumsum(AST_home) - AST_home)
cumsum_support = cumsum_support %>% group_by(a_temp_id) %>% mutate(TOT_AST_AWAY = cumsum(AST_away) - AST_away)
```

```{r}
#Avg AST Differential 
cumsum_support = cumsum_support %>% mutate(AST_DIF_HOME = AST_home - AST_away)
cumsum_support = cumsum_support %>% mutate(AST_DIF_AWAY = AST_away - AST_home)

cumsum_support = cumsum_support %>% group_by(h_temp_id) %>% mutate(AVG_AST_DIF_HOME = round(lag(cummean(AST_DIF_HOME)),3))
cumsum_support = cumsum_support %>% group_by(a_temp_id) %>% mutate(AVG_AST_DIF_AWAY = round(lag(cummean(AST_DIF_AWAY)),3))
```

```{r}
#TOT_REB_HOME and TOT_REB_AWAY
cumsum_support = cumsum_support %>% group_by(h_temp_id) %>% mutate(TOT_REB_HOME = cumsum(REB_home) - REB_home)
cumsum_support = cumsum_support %>% group_by(a_temp_id) %>% mutate(TOT_REB_AWAY = cumsum(REB_away) - REB_away)
```

```{r}
#Avg REB Differential 
cumsum_support = cumsum_support %>% mutate(REB_DIF_HOME = REB_home - REB_away)
cumsum_support = cumsum_support %>% mutate(REB_DIF_AWAY = REB_away - REB_home)

cumsum_support = cumsum_support %>% group_by(h_temp_id) %>% mutate(AVG_REB_DIF_HOME = round(lag(cummean(REB_DIF_HOME)),3))
cumsum_support = cumsum_support %>% group_by(a_temp_id) %>% mutate(AVG_REB_DIF_AWAY = round(lag(cummean(REB_DIF_AWAY)),3))
```

```{r}
cumsum_support[is.na(cumsum_support)] <- 0
```

```{r}
#Data for Last 3 games
library(zoo)
last3_support = cumsum_support %>% group_by(h_temp_id) %>% mutate(PTLast3_Home = lag(rollapplyr(PTS_home, 3, sum, partial = TRUE)))
last3_support = last3_support %>% group_by(a_temp_id) %>% mutate(PTLast3_Away = lag(rollapplyr(PTS_away, 3, sum, partial = TRUE)))                        

last3_support = last3_support %>% group_by(h_temp_id) %>% mutate(REBLast3_Home = lag(rollapplyr(REB_home, 3, sum, partial = TRUE)))
last3_support = last3_support %>% group_by(a_temp_id) %>% mutate(REBLast3_Away = lag(rollapplyr(REB_away, 3, sum, partial = TRUE)))   

last3_support = last3_support %>% group_by(h_temp_id) %>% mutate(ASTLast3_Home = lag(rollapplyr(AST_home, 3, sum, partial = TRUE)))
last3_support = last3_support %>% group_by(a_temp_id) %>% mutate(ASTLast3_Away = lag(rollapplyr(AST_away, 3, sum, partial = TRUE)))   

last3_support = last3_support %>% group_by(h_temp_id) %>% mutate(FG_PCTLast3_Home = round(lag(rollapplyr(FG_PCT_home, 3, mean, partial = TRUE)),3))
last3_support = last3_support %>% group_by(a_temp_id) %>% mutate(FG_PCTLast3_Away = round(lag(rollapplyr(FG_PCT_away, 3, mean, partial = TRUE)),3)) 

last3_support = last3_support %>% group_by(h_temp_id) %>% mutate(FT_PCTLast3_Home = round(lag(rollapplyr(FT_PCT_home, 3, mean, partial = TRUE)),3))
last3_support = last3_support %>% group_by(a_temp_id) %>% mutate(FT_PCTLast3_Away = round(lag(rollapplyr(FT_PCT_away, 3, mean, partial = TRUE)),3)) 

last3_support = last3_support %>% group_by(h_temp_id) %>% mutate(FG3_PCTLast3_Home = round(lag(rollapplyr(FG3_PCT_home, 3, mean, partial = TRUE)),3))
last3_support = last3_support %>% group_by(a_temp_id) %>% mutate(FG3_PCTLast3_Away = round(lag(rollapplyr(FG3_PCT_away, 3, mean, partial = TRUE)),3))

```

```{r}
last3_support[is.na(last3_support)] <- 0
```

```{r}
master_games = last3_support
#Removing Target Leakage columns

keeps = c("GAME_DATE_EST", "GAME_ID", "SEASON", "TEAM_ID_home", "TEAM_ID_away", "HT_G","HT_W_PCT", "HT_HOME_W_PCT", "HT_ROAD_W_PCT", "TOT_PTS_HOME", "AVG_PT_DIF_HOME", "AVG_FG_PCT_HOME", "AVG_FT_PCT_HOME", "AVG_FG3_PCT_HOME", "TOT_AST_HOME", "TOT_REB_HOME", "AVG_AST_DIF_HOME","AVG_REB_DIF_HOME", "PTLast3_Home", "REBLast3_Home", "ASTLast3_Home", "FG_PCTLast3_Home", "FT_PCTLast3_Home","FG3_PCTLast3_Home","AT_G","AT_W_PCT", "AT_HOME_W_PCT", "AT_ROAD_W_PCT", "TOT_PTS_AWAY", "AVG_PT_DIF_AWAY", "AVG_FG_PCT_AWAY", "AVG_FT_PCT_AWAY", "AVG_FG3_PCT_AWAY", "TOT_AST_AWAY", "TOT_REB_AWAY", "AVG_AST_DIF_AWAY","AVG_REB_DIF_AWAY", "PTLast3_Away", "REBLast3_Away", "ASTLast3_Away", "FG_PCTLast3_Away", "FT_PCTLast3_Away","FG3_PCTLast3_Away", "HOME_TEAM_WINS")

master_games = master_games[keeps]

```

```{r}
#Writing New Dataset to CSV
write.csv(master_games, "C:/Users/deang/Documents/DS504/Project/master_games.csv", row.names = FALSE)
```

